### ISSUE TITLE
Packer SSH handshake bug

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision-aws#9]
@jamesmcclain reported that:

"The packer build fails with the latest Deep Learning AMI (Version 21):

![screenshot_2019-01-31_19-16-39](https://user-images.githubusercontent.com/11281373/52096886-93698900-2596-11e9-9225-12531fccb2d1.png)

That seems to be a well-known issue (see [here](https://github.com/hashicorp/packer/issues/6645) and [here](https://github.com/hashicorp/packer/issues/788)) in various contexts. "

I tried this and was able to run the job. So this makes me think it's an intermittent problem.

**Comment by jeancochrane** [comment]
I was unable to replicate this either with the latest DL Base AMI recommended by the docs (version 16.2, `ami-003c401895188b246`) or the latest DL non-Base AMI that I suspect @jamesmcclain was using (version 21.2, `ami-087379093eeda94ae`). I tried on MacOS Mojave and Ubuntu 16.04.

Since this issue appears intermittent, I opened up #13 to remove the reference to the issue from the docs. I figure that anyone who runs into the problem again should be able to find this issue by searching for it.

**Comment by jamesmcclain** [comment]
> I was unable to replicate this either with the latest DL Base AMI recommended by the docs (version 16.2, `ami-003c401895188b246`) or the latest DL non-Base AMI that I suspect @jamesmcclain was using (version 21.2, `ami-087379093eeda94ae`). I tried on MacOS Mojave and Ubuntu 16.04.
> 
> Since this issue appears intermittent, I opened up #13 to remove the reference to the issue from the docs. I figure that anyone who runs into the problem again should be able to find this issue by searching for it.

Okay, sounds good.
